### PR TITLE
fix: YAML loading to support Ruby 3.1

### LINKED ISSUE #34: This gem doesn't work on Ruby 3.1 due to a breaking change of `YAML#load`
Ruby 3.1 comes with Psych 4.0 bundled, which changes `YAML#load` to behave like `YAML#safe_load` (instead of `YAML#unsafe_load`). See https://github.com/ruby/psych/pull/487 for more details.

This results in `Psych::DisallowedClass: Tried to load unspecified class:` for all registered async subscriber classes.

### PR DESCRIPTION
**Pull request by SeanLF**
* fixes #34 
* adds latest rubies (2.7, 3.0, 3.1) to CI

Tests pass: https://app.travis-ci.com/github/SeanLF/wisper-sidekiq/builds/252328283
Green build

### CODE REVIEW

**Comment by SeanLF** [comment]
@krisleech Can you please let me know if you'd like me to change anything?

FYI, it looks like you're still using `travis-ci.org`: 
> Since June 15th, 2021, the building on [travis-ci.org](http://www.travis-ci.org/) is ceased. Please use [travis-ci.com](http://www.travis-ci.com/) from now on.

**Comment by SeanLF** [comment]
@krisleech any chance I could get a review?

**Comment by GMorris-professional** [comment]
@SeanLF, thanks for the fix, we implemented a similar fix to yours but instead passed in the parameters permitted_classes and aliases:  ```::Yaml.load(yml, permitted_classes: [Symbol, Time], aliases: true)```. I must admit I am not 100% familiar with all the workings of ::Yaml and Psych but do you think it may be worth working on a fix that uses the normal load ("safe_load" under the hood) with the new required parameters?

**Comment by SeanLF** [comment]
@GMorris-professional It's indeed better to use permitted classes, but might make more sense to make the permitted class list a configuration option for the gem

**Pull request closed without merging**
