### PR TITLE
Allow setting job options with a job_options method on the listener

### PR DESCRIPTION
**Pull request by bencrouse**
I'm loving this gem, but I need to be able to set various options (e.g. queue name, retry) per listener. I figured this was the most unobtrusive way to achieve this. I would have liked to be able to code something like:

``` ruby
Wisper.subscribe(MyListener, async: true, queue: 'test', retry: false)
```

but couldn't figure out how to make this work since the options aren't saved with the Registration. Might be worth changing in Wisper.

If you have ideas for a better implementation, let me know and I'll take care of it.

### CODE REVIEW

**Comment by jcavalieri** [comment]
This would be sweet:

```Wisper.subscribe(MyListener).async(queue: 'test', retry: false)```

I'd love to see this too.

**Comment by bencrouse** [comment]
i ended up writing my own broadcaster which does something similar to this pr - but i totally think this is still a great idea. i started getting into the wisper changes required, but had to timebox myself and ran out of time.

**Comment by jcavalieri** [comment]
I was thinking about that too.

Quick question, I hope, is retry on by default? It is a little hard to tell from the documentation.

**Comment by jcavalieri** [comment]
Ahh, found it, it is on by default:

https://github.com/mperham/sidekiq/blob/adb8e1ed48cedf513c37bf960b9043bfd70af3f8/lib/sidekiq.rb#L35-L38

**Comment by dmichael** [comment]
Not sure if this was ever resolved. I have forked @bencrouse 's wisper-sidekiq to allow for extra options. It is an elegant and simple solution to the issue of passing in additional sidekiq options without changing the Wisper signature for async. Thanks!

**Pull request closed without merging**
